import { useState } from 'react';
import { ArrowLeft, Trophy, Clock, Target, CheckCircle, XCircle, RefreshCw, Download, Share2, Award, Star, TrendingUp, Eye, BookOpen } from 'lucide-react';
import { Button } from './ui/button';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Alert, AlertDescription } from './ui/alert';
import { Separator } from './ui/separator';
import { toast } from 'sonner';

interface Assessment {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  duration: number;
  totalQuestions: number;
  passingScore: number;
  skills: string[];
}

interface AssessmentResult {
  id: string;
  assessmentId: string;
  userId: string;
  score: number;
  percentage: number;
  timeSpent: number;
  startedAt: string;
  completedAt: string;
  passed: boolean;
  answers: AssessmentAnswer[];
  skillBreakdown: SkillScore[];
}

interface AssessmentAnswer {
  questionId: string;
  selectedAnswer: string | string[];
  isCorrect: boolean;
  timeSpent: number;
}

interface SkillScore {
  skill: string;
  score: number;
  maxScore: number;
  percentage: number;
}

interface AssessmentResultsProps {
  result: AssessmentResult;
  assessment: Assessment;
  onBack: () => void;
  onRetake: () => void;
}

export function AssessmentResults({ result, assessment, onBack, onRetake }: AssessmentResultsProps) {
  const [showAnswers, setShowAnswers] = useState(false);

  const formatTime = (seconds: number) => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const remainingSeconds = seconds % 60;
    
    if (hours > 0) {
      return `${hours}h ${minutes}m ${remainingSeconds}s`;
    }
    return `${minutes}m ${remainingSeconds}s`;
  };

  const getPerformanceLevel = (percentage: number) => {
    if (percentage >= 90) return { level: 'Excellent', color: 'text-green-600', bg: 'bg-green-100' };
    if (percentage >= 80) return { level: 'Good', color: 'text-blue-600', bg: 'bg-blue-100' };
    if (percentage >= 70) return { level: 'Fair', color: 'text-yellow-600', bg: 'bg-yellow-100' };
    return { level: 'Needs Improvement', color: 'text-red-600', bg: 'bg-red-100' };
  };

  const performance = getPerformanceLevel(result.percentage);

  const handleShare = () => {
    const shareText = `I just completed the ${assessment.title} assessment and scored ${result.percentage}%! ${result.passed ? 'ðŸŽ‰' : ''}`;
    
    if (navigator.share) {
      navigator.share({
        title: 'Assessment Results',
        text: shareText,
        url: window.location.href
      });
    } else {
      navigator.clipboard.writeText(shareText);
      toast.success('Results copied to clipboard!');
    }
  };

  const handleDownload = () => {
    const content = `
Assessment Results
==================

Assessment: ${assessment.title}
Category: ${assessment.category}
Difficulty: ${assessment.difficulty}
Completed: ${new Date(result.completedAt).toLocaleString()}

Results:
--------
Score: ${result.score}/${assessment.totalQuestions} (${result.percentage}%)
Status: ${result.passed ? 'PASSED' : 'FAILED'}
Time Spent: ${formatTime(result.timeSpent)}
Performance Level: ${performance.level}

Skill Breakdown:
${result.skillBreakdown.map(skill => 
  `- ${skill.skill}: ${skill.score}/${skill.maxScore} (${skill.percentage}%)`
).join('\n')}

Generated by HireVify Skills Assessment Platform
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `assessment-results-${assessment.title.replace(/\s+/g, '-').toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success('Results downloaded successfully!');
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-6xl mx-auto px-6 py-8">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Button variant="ghost" onClick={onBack} className="p-2">
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <div className="flex-1">
            <h1 className="text-3xl font-bold text-foreground">Assessment Results</h1>
            <p className="text-muted-foreground">{assessment.title}</p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={handleShare}>
              <Share2 className="w-4 h-4 mr-2" />
              Share
            </Button>
            <Button variant="outline" onClick={handleDownload}>
              <Download className="w-4 h-4 mr-2" />
              Download
            </Button>
          </div>
        </div>

        {/* Result Overview */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
          {/* Main Score Card */}
          <div className="lg:col-span-2">
            <Card className={`border-2 ${result.passed ? 'border-success bg-success/5' : 'border-error bg-error/5'}`}>
              <CardContent className="p-8 text-center">
                <div className="flex items-center justify-center mb-6">
                  {result.passed ? (
                    <div className="w-20 h-20 bg-success/10 rounded-full flex items-center justify-center">
                      <Trophy className="w-10 h-10 text-success" />
                    </div>
                  ) : (
                    <div className="w-20 h-20 bg-error/10 rounded-full flex items-center justify-center">
                      <XCircle className="w-10 h-10 text-error" />
                    </div>
                  )}
                </div>
                
                <h2 className="text-4xl font-bold text-foreground mb-2">{result.percentage}%</h2>
                <p className="text-xl font-medium mb-4">
                  {result.score} out of {assessment.totalQuestions} correct
                </p>
                
                <Badge className={`text-lg px-4 py-2 ${result.passed 
                  ? 'bg-success text-success-foreground' 
                  : 'bg-error text-error-foreground'
                }`}>
                  {result.passed ? 'PASSED' : 'FAILED'}
                </Badge>
                
                <div className="mt-6">
                  <div className={`inline-flex items-center px-4 py-2 rounded-full ${performance.bg}`}>
                    <Star className={`w-4 h-4 mr-2 ${performance.color}`} />
                    <span className={`font-medium ${performance.color}`}>
                      {performance.level}
                    </span>
                  </div>
                </div>

                {result.passed && (
                  <Alert className="mt-6 border-success bg-success/10">
                    <Award className="h-4 w-4 text-success" />
                    <AlertDescription className="text-success">
                      Congratulations! You've earned a certification in {assessment.title}.
                      This demonstrates your proficiency in {assessment.skills.join(', ')}.
                    </AlertDescription>
                  </Alert>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Stats Sidebar */}
          <div className="space-y-4">
            <Card>
              <CardContent className="p-6">
                <div className="flex items-center mb-4">
                  <Clock className="w-5 h-5 text-muted-foreground mr-3" />
                  <span className="font-medium text-foreground">Time Spent</span>
                </div>
                <p className="text-2xl font-bold text-foreground">{formatTime(result.timeSpent)}</p>
                <p className="text-sm text-muted-foreground mt-1">
                  Average: {Math.round(result.timeSpent / assessment.totalQuestions)}s per question
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center mb-4">
                  <Target className="w-5 h-5 text-muted-foreground mr-3" />
                  <span className="font-medium text-foreground">Passing Score</span>
                </div>
                <p className="text-2xl font-bold text-foreground">{assessment.passingScore}%</p>
                <p className="text-sm text-muted-foreground mt-1">
                  You scored {result.percentage - assessment.passingScore > 0 ? '+' : ''}{result.percentage - assessment.passingScore}% vs. required
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center mb-4">
                  <TrendingUp className="w-5 h-5 text-muted-foreground mr-3" />
                  <span className="font-medium text-foreground">Difficulty</span>
                </div>
                <Badge className={`text-lg px-3 py-1 ${
                  assessment.difficulty === 'beginner' ? 'bg-green-100 text-green-800 border-green-200' :
                  assessment.difficulty === 'intermediate' ? 'bg-yellow-100 text-yellow-800 border-yellow-200' :
                  'bg-red-100 text-red-800 border-red-200'
                }`}>
                  {assessment.difficulty}
                </Badge>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Detailed Results */}
        <Tabs defaultValue="skills" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="skills">Skill Breakdown</TabsTrigger>
            <TabsTrigger value="performance">Performance Analysis</TabsTrigger>
            <TabsTrigger value="review">Review Questions</TabsTrigger>
          </TabsList>

          <TabsContent value="skills" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Skills Performance</CardTitle>
                <p className="text-muted-foreground">
                  See how you performed in each skill area covered by this assessment.
                </p>
              </CardHeader>
              <CardContent>
                <div className="space-y-6">
                  {result.skillBreakdown.map((skill, index) => (
                    <div key={index} className="space-y-3">
                      <div className="flex items-center justify-between">
                        <h4 className="font-medium text-foreground">{skill.skill}</h4>
                        <div className="text-right">
                          <span className="font-bold text-foreground">{skill.percentage}%</span>
                          <span className="text-sm text-muted-foreground ml-2">
                            ({skill.score}/{skill.maxScore})
                          </span>
                        </div>
                      </div>
                      
                      <Progress value={skill.percentage} className="h-3" />
                      
                      <div className="flex items-center justify-between text-sm">
                        <span className={`font-medium ${
                          skill.percentage >= 80 ? 'text-success' :
                          skill.percentage >= 60 ? 'text-warning' :
                          'text-error'
                        }`}>
                          {skill.percentage >= 80 ? 'Strong' :
                           skill.percentage >= 60 ? 'Good' : 'Needs Work'}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="performance" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Strengths</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {result.skillBreakdown
                      .filter(skill => skill.percentage >= 75)
                      .map((skill, index) => (
                        <div key={index} className="flex items-center gap-3">
                          <CheckCircle className="w-5 h-5 text-success" />
                          <div>
                            <p className="font-medium text-foreground">{skill.skill}</p>
                            <p className="text-sm text-muted-foreground">{skill.percentage}% mastery</p>
                          </div>
                        </div>
                      ))}
                    {result.skillBreakdown.filter(skill => skill.percentage >= 75).length === 0 && (
                      <p className="text-muted-foreground">No skills achieved 75% or higher mastery.</p>
                    )}
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Areas for Improvement</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {result.skillBreakdown
                      .filter(skill => skill.percentage < 70)
                      .map((skill, index) => (
                        <div key={index} className="flex items-center gap-3">
                          <XCircle className="w-5 h-5 text-error" />
                          <div>
                            <p className="font-medium text-foreground">{skill.skill}</p>
                            <p className="text-sm text-muted-foreground">{skill.percentage}% mastery</p>
                          </div>
                        </div>
                      ))}
                    {result.skillBreakdown.filter(skill => skill.percentage < 70).length === 0 && (
                      <p className="text-muted-foreground">Great job! All skills achieved 70% or higher mastery.</p>
                    )}
                  </div>
                </CardContent>
              </Card>
            </div>

            <Card>
              <CardHeader>
                <CardTitle>Recommendations</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {result.passed ? (
                    <Alert className="border-success bg-success/5">
                      <Trophy className="h-4 w-4 text-success" />
                      <AlertDescription className="text-success">
                        Excellent work! You've demonstrated strong competency in {assessment.title}.
                        Consider taking advanced assessments in related areas to further validate your expertise.
                      </AlertDescription>
                    </Alert>
                  ) : (
                    <Alert className="border-warning bg-warning/5">
                      <BookOpen className="h-4 w-4 text-warning" />
                      <AlertDescription className="text-warning">
                        Focus on studying the areas where you scored below 70%. 
                        Consider additional practice and retaking the assessment when you feel more prepared.
                      </AlertDescription>
                    </Alert>
                  )}
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="p-4 border border-border rounded-lg">
                      <h4 className="font-medium text-foreground mb-2">Next Steps</h4>
                      <ul className="text-sm text-muted-foreground space-y-1">
                        <li>â€¢ Review incorrect answers</li>
                        <li>â€¢ Study weak skill areas</li>
                        <li>â€¢ Practice with similar questions</li>
                        <li>â€¢ Consider retaking in 1-2 weeks</li>
                      </ul>
                    </div>
                    
                    <div className="p-4 border border-border rounded-lg">
                      <h4 className="font-medium text-foreground mb-2">Resources</h4>
                      <ul className="text-sm text-muted-foreground space-y-1">
                        <li>â€¢ Online tutorials and courses</li>
                        <li>â€¢ Practice coding challenges</li>
                        <li>â€¢ Documentation and guides</li>
                        <li>â€¢ Community forums and help</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="review" className="space-y-6">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>Question Review</CardTitle>
                    <p className="text-muted-foreground">
                      Review your answers and see the correct solutions.
                    </p>
                  </div>
                  <Button
                    variant="outline"
                    onClick={() => setShowAnswers(!showAnswers)}
                  >
                    <Eye className="w-4 h-4 mr-2" />
                    {showAnswers ? 'Hide' : 'Show'} Answers
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                {showAnswers ? (
                  <div className="space-y-6">
                    {result.answers.map((answer, index) => (
                      <div key={index} className="p-4 border border-border rounded-lg">
                        <div className="flex items-start justify-between mb-3">
                          <div className="flex items-center gap-2">
                            <span className="font-medium text-foreground">Question {index + 1}</span>
                            {answer.isCorrect ? (
                              <CheckCircle className="w-5 h-5 text-success" />
                            ) : (
                              <XCircle className="w-5 h-5 text-error" />
                            )}
                          </div>
                          <Badge variant={answer.isCorrect ? "default" : "destructive"}>
                            {answer.isCorrect ? 'Correct' : 'Incorrect'}
                          </Badge>
                        </div>
                        
                        <div className="space-y-3">
                          <div>
                            <p className="font-medium text-foreground mb-2">Your Answer:</p>
                            <p className="text-muted-foreground">
                              {Array.isArray(answer.selectedAnswer) 
                                ? answer.selectedAnswer.join(', ') 
                                : answer.selectedAnswer || 'No answer provided'
                              }
                            </p>
                          </div>
                          
                          {!answer.isCorrect && (
                            <div>
                              <p className="font-medium text-success mb-2">Correct Answer:</p>
                              <p className="text-success">Sample correct answer would go here</p>
                            </div>
                          )}
                          
                          <div className="text-xs text-muted-foreground">
                            Time spent: {Math.round(answer.timeSpent / 1000)}s
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8">
                    <Eye className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                    <p className="text-muted-foreground">
                      Click "Show Answers" to review your responses and see correct solutions.
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Action Buttons */}
        <div className="flex items-center justify-center gap-4 mt-8">
          <Button variant="outline" onClick={onBack}>
            Back to Assessments
          </Button>
          <Button onClick={onRetake}>
            <RefreshCw className="w-4 h-4 mr-2" />
            Retake Assessment
          </Button>
        </div>
      </div>
    </div>
  );
}







