import { useState } from 'react';
import { 
  Target, 
  TrendingUp, 
  CheckCircle, 
  AlertCircle, 
  Star, 
  Download, 
  RefreshCw, 
  Eye,
  ArrowLeft,
  User,
  Briefcase,
  GraduationCap,
  Award,
  Zap,
  Lightbulb,
  FileText,
  BarChart3,
  Shield,
  X
} from 'lucide-react';
import { Button } from './ui/button';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { Separator } from './ui/separator';
import { toast } from 'sonner';

interface ATSResultsProps {
  results: any;
  isOpen: boolean;
  onClose: () => void;
  onNewScan: () => void;
}

export function CandidateATSResults({ results, isOpen, onClose, onNewScan }: ATSResultsProps) {
  const [showFullDetails, setShowFullDetails] = useState(false);

  if (!results) return null;

  const getScoreColor = (score: number) => {
    if (score >= 85) return 'bg-green-100 text-green-800 border-green-200';
    if (score >= 70) return 'bg-yellow-100 text-yellow-800 border-yellow-200';
    return 'bg-red-100 text-red-800 border-red-200';
  };

  const getScoreText = (score: number) => {
    if (score >= 90) return 'Excellent';
    if (score >= 80) return 'Good';
    if (score >= 70) return 'Fair';
    return 'Needs Improvement';
  };

  const downloadResults = () => {
    const reportContent = `
HireVify ATS Analysis Report
Generated: ${new Date().toLocaleDateString()}

CANDIDATE: ${results.personalInfo?.name || 'N/A'}
EMAIL: ${results.personalInfo?.email || 'N/A'}
FILE: ${results.fileName || 'N/A'}

OVERALL ATS SCORE: ${results.atsScore?.overall || 0}% (${getScoreText(results.atsScore?.overall || 0)})

SCORE BREAKDOWN:
• Formatting: ${results.atsScore?.breakdown?.formatting || 0}%
• Keywords: ${results.atsScore?.breakdown?.keywords || 0}%
• Readability: ${results.atsScore?.breakdown?.readability || 0}%
• Completeness: ${results.atsScore?.breakdown?.completeness || 0}%
• ATS Compatibility: ${results.atsScore?.breakdown?.atsCompatibility || 0}%

TOP RECOMMENDATIONS:
${results.atsScore?.recommendations?.map((rec: string, i: number) => `${i + 1}. ${rec}`).join('\n') || 'None available'}

IDENTIFIED STRENGTHS:
${results.atsScore?.strengths?.map((strength: string, i: number) => `• ${strength}`).join('\n') || 'None identified'}

AREAS FOR IMPROVEMENT:
${results.atsScore?.improvements?.map((improvement: string, i: number) => `• ${improvement}`).join('\n') || 'None identified'}

TECHNICAL SKILLS FOUND:
${results.skills?.technical?.join(', ') || 'None identified'}

SOFT SKILLS FOUND:
${results.skills?.soft?.join(', ') || 'None identified'}

CAREER INSIGHTS:
• Hirability Score: ${results.insights?.hirabilityScore || 'N/A'}%
• Market Position: ${results.insights?.marketPositioning?.competitiveness || 'N/A'}
• Estimated Salary Range: ${results.insights?.marketPositioning?.salaryRange || 'N/A'}
• Next Career Step: ${results.insights?.careerProgression?.nextRole || 'N/A'}

PROCESSING DETAILS:
• Method: ${results.processingMetadata?.processingMethod || 'Standard Processing'}
• Confidence: ${Math.round((results.processingMetadata?.confidence || 0) * 100)}%
• Analysis Version: ${results.processingMetadata?.version || 'N/A'}

This analysis was generated by HireVify's advanced ATS compatibility scanner.
For best results, address the recommendations above and re-scan your resume.
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `HireVify_ATS_Analysis_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success('📄 ATS analysis report downloaded successfully!');
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center justify-between">
            <DialogTitle className="flex items-center text-xl">
              <Target className="w-6 h-6 mr-2 text-blue-600" />
              Your ATS Analysis Results
            </DialogTitle>
            <Button variant="ghost" size="sm" onClick={onClose}>
              <X className="w-4 h-4" />
            </Button>
          </div>
          <DialogDescription>
            Comprehensive analysis of your resume's ATS compatibility, including scores, recommendations, and career insights to help you optimize your job applications.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {/* Overall Score Header */}
          <div className="bg-gradient-to-r from-blue-50 to-green-50 rounded-lg p-6 border border-blue-200">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">Overall ATS Compatibility Score</h3>
                <p className="text-sm text-gray-600">How well your resume performs against Applicant Tracking Systems</p>
              </div>
              <div className="text-right">
                <div className="text-4xl font-bold text-blue-600 mb-1">
                  {results.atsScore?.overall || 0}%
                </div>
                <Badge className={`${getScoreColor(results.atsScore?.overall || 0)} font-semibold`}>
                  {getScoreText(results.atsScore?.overall || 0)}
                </Badge>
              </div>
            </div>
            
            <div className="mb-4">
              <Progress value={results.atsScore?.overall || 0} className="h-3" />
            </div>

            {results.insights?.hirabilityScore && (
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-700">Hirability Score:</span>
                <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                  {results.insights.hirabilityScore}% Hirable
                </Badge>
              </div>
            )}
          </div>

          {/* Score Breakdown */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center">
                <BarChart3 className="w-5 h-5 mr-2 text-blue-600" />
                Detailed Score Breakdown
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {results.atsScore?.breakdown && Object.entries(results.atsScore.breakdown).map(([category, score]: [string, any]) => (
                  <div key={category} className="flex items-center justify-between">
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-sm font-medium capitalize text-gray-700">
                          {category.replace(/([A-Z])/g, ' $1').trim()}
                        </span>
                        <span className="text-sm font-semibold text-gray-900">{score}%</span>
                      </div>
                      <Progress value={score} className="h-2" />
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Key Recommendations */}
          {results.atsScore?.recommendations && results.atsScore.recommendations.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Lightbulb className="w-5 h-5 mr-2 text-yellow-600" />
                  Priority Recommendations
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {results.atsScore.recommendations.map((recommendation: string, index: number) => (
                    <div key={index} className="flex items-start space-x-3 p-3 bg-yellow-50 rounded-lg border border-yellow-200">
                      <div className="flex-shrink-0 w-6 h-6 bg-yellow-200 rounded-full flex items-center justify-center text-xs font-semibold text-yellow-800">
                        {index + 1}
                      </div>
                      <p className="text-sm text-yellow-800 flex-1">{recommendation}</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Strengths and Improvements */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Strengths */}
            {results.atsScore?.strengths && results.atsScore.strengths.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center text-green-700">
                    <CheckCircle className="w-5 h-5 mr-2" />
                    Resume Strengths
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {results.atsScore.strengths.map((strength: string, index: number) => (
                      <div key={index} className="flex items-center space-x-2 text-sm">
                        <CheckCircle className="w-4 h-4 text-green-600 flex-shrink-0" />
                        <span className="text-green-800">{strength}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Improvements */}
            {results.atsScore?.improvements && results.atsScore.improvements.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center text-orange-700">
                    <TrendingUp className="w-5 h-5 mr-2" />
                    Areas to Improve
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {results.atsScore.improvements.map((improvement: string, index: number) => (
                      <div key={index} className="flex items-center space-x-2 text-sm">
                        <AlertCircle className="w-4 h-4 text-orange-600 flex-shrink-0" />
                        <span className="text-orange-800">{improvement}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </div>

          {/* Skills Analysis */}
          {results.skills && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Award className="w-5 h-5 mr-2 text-purple-600" />
                  Skills Analysis
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {results.skills.technical && results.skills.technical.length > 0 && (
                    <div>
                      <h4 className="font-medium text-gray-900 mb-3 flex items-center">
                        <Zap className="w-4 h-4 mr-1 text-blue-600" />
                        Technical Skills Detected
                      </h4>
                      <div className="flex flex-wrap gap-2">
                        {results.skills.technical.map((skill: string, index: number) => (
                          <Badge key={index} variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
                            {skill}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}
                  
                  {results.skills.soft && results.skills.soft.length > 0 && (
                    <div>
                      <h4 className="font-medium text-gray-900 mb-3 flex items-center">
                        <User className="w-4 h-4 mr-1 text-green-600" />
                        Soft Skills Detected
                      </h4>
                      <div className="flex flex-wrap gap-2">
                        {results.skills.soft.map((skill: string, index: number) => (
                          <Badge key={index} variant="outline" className="bg-green-50 text-green-700 border-green-200">
                            {skill}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Career Insights */}
          {results.insights && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Star className="w-5 h-5 mr-2 text-indigo-600" />
                  Career Market Insights
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {results.insights.marketPositioning?.competitiveness && (
                    <div className="text-center p-4 bg-indigo-50 rounded-lg">
                      <div className="text-lg font-semibold text-indigo-900 mb-1">
                        {results.insights.marketPositioning.competitiveness}
                      </div>
                      <div className="text-xs text-indigo-700">Market Position</div>
                    </div>
                  )}
                  
                  {results.insights.marketPositioning?.salaryRange && (
                    <div className="text-center p-4 bg-green-50 rounded-lg">
                      <div className="text-lg font-semibold text-green-900 mb-1">
                        {results.insights.marketPositioning.salaryRange}
                      </div>
                      <div className="text-xs text-green-700">Estimated Salary</div>
                    </div>
                  )}
                  
                  {results.insights.careerProgression?.nextRole && (
                    <div className="text-center p-4 bg-purple-50 rounded-lg">
                      <div className="text-lg font-semibold text-purple-900 mb-1">
                        {results.insights.careerProgression.nextRole}
                      </div>
                      <div className="text-xs text-purple-700">Next Career Step</div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-3 pt-6 border-t">
            <Button onClick={downloadResults} className="flex-1">
              <Download className="w-4 h-4 mr-2" />
              Download Full Report
            </Button>
            <Button onClick={onNewScan} variant="outline" className="flex-1">
              <RefreshCw className="w-4 h-4 mr-2" />
              Scan Another Resume
            </Button>
            <Button onClick={onClose} variant="outline">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Close Results
            </Button>
          </div>

          {/* Processing Info */}
          {results.processingMetadata && (
            <div className="text-xs text-gray-500 text-center pt-4 border-t">
              <div className="flex items-center justify-center space-x-4">
                <span>Processed with {results.processingMetadata.processingMethod}</span>
                <Separator orientation="vertical" className="h-3" />
                <span>Confidence: {Math.round((results.processingMetadata.confidence || 0) * 100)}%</span>
                <Separator orientation="vertical" className="h-3" />
                <span>Version: {results.processingMetadata.version || 'Standard'}</span>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}





