export const MAX_SKILLS_PER_FORM = 12;

export const SKILL_OPTIONS = [
 'React',
 'Next.js',
 'TypeScript',
 'JavaScript',
 'Node.js',
 'Python',
 'Java',
 'Go',
 'Rust',
 'HTML',
 'CSS',
 'Tailwind CSS',
 'UI/UX Design',
 'Figma',
 'Product Management',
 'Project Management',
 'QA Testing',
 'Automation Testing',
 'API Design',
 'REST APIs',
 'GraphQL',
 'PostgreSQL',
 'MongoDB',
 'Supabase',
 'Firebase',
 'AWS',
 'Azure',
 'Google Cloud',
 'Docker',
 'Kubernetes',
 'DevOps',
 'CI/CD',
 'Data Science',
 'Machine Learning',
 'SQL',
 'Business Analytics',
 'Cybersecurity',
 'Technical Writing',
 'Communication',
 'Leadership',
] as const;
